networks:
  appnetwork:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-milhouse
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      # - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
    networks:
      - appnetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-milhouse
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
    ports:
      - "${PORT_PHP_MAPPING:-9000}:9000"      
    networks:
      - appnetwork
